### ISSUE TITLE
'accountId' not accepted by b2_list_file_names API

### ISSUE THREAD

**Issue by 357r4bd** [ericschernoff/Backblaze-B2V2Client#5]
PR forthcoming.

**Comment by 357r4bd** [comment]
btw, I wasn't needing the other calls so I do not know if any others are affected by the actual bug here or if it represents a change in the B2 API just for this call. In any case you may want to audit the calls to make sure they do or do not accept `accountId`.

**Comment by ericschernoff** [comment]
Hi there,

I am really, really sorry that I somehow missed this awesome issue and pull-request. I have all the GitHub notifications turned on, but for some reason, they get filtered out by Gmail.  I am really sorry that I somehow missed this for FOUR months.  I promise I was not ignoring you; I was just obtuse.

Anyhow, this is an excellent pull-request.  I am going to merge it in and test it right now, and hopefully have it on CPAN ASAP.  Update shortly...

-Eric

**Comment by ericschernoff** [comment]
Hello,

I have implemented your improvements to b2_list_file_names() with just a minor change:  Rather than take a flat list of args, I have that method accepting the buck_name then a %args hash so the user can chose which params to send:

```
$results = $b2client->b2_list_file_names('HarmonyFiles',(
	'maxFileCount' => 25,
	'startFileName' => '10162.zip',
));
```

I also modified all the other methods to return the 'current_status' of "OK' or 'Error'.  I'm kind of embarrassed everything didn't already return something, as I finally (after 24 years) just learned what kind of a mess you can make by not returning a value.  It has been a bad habit not to do that before.

I did check through all the other B2 endpoints to make sure I wasn't sending accountId incorrectly, and the b2_list_file_names was the only one where it could be removed; the other endpoints where I am sending accountId still call for it.

Thank you for (a) using this module, (b) submitting this great PR, and (c) being patient for this update.

I have released the update to CPAN, so I am closing this issue.  Please email me directly at ericschernoff@gmail.com to discuss further.

-Eric
